version: "3.8"
services:
  qemu:
    container_name: qemu
    build: .
    image: tailnet-qemu:0.0.1-beta
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    environment:
      - BOOT=proxmox
      - USER_PORTS=8006,22,5900
      - NETWORK=passt
      # Injects Slirp networks (IPv4 + IPv6) AND the fw_cfg script seamlessly
      - ARGUMENTS="-netdev user,id=net1,net=172.18.0.0/24,ipv6=on,ipv6-net=fd00:18::/64 -device virtio-net-pci,netdev=net1 -netdev user,id=net2,net=124.10.0.0/24,ipv6=on,ipv6-net=fd00:10::/64 -device virtio-net-pci,netdev=net2 -fw_cfg name=opt/net-setup.sh,file=/run/net-setup.sh"

