version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: qemu-tty
    hostname: qemu-tty
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--ssh --accept-dns=false
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - tailnet-state:/var/lib/tailscale
    restart: always
    networks:
      - zone1
      - zone2

  qemu:
    container_name: qemu
    build: ..
    image: tailnet-qemu:0.0.1-beta
    devices:
      - /dev/kvm
    privileged: true
    volumes:
      - ./qemu:/storage2
      - ./tmp:/storage
      - ..:/workspaces/tailnet-podman
    restart: on-failure
    stop_grace_period: 2m
    network_mode: bridge
    depends_on:
      - tailscale
    networks:
      zone1:
        ipv4_address: 172.18.0.100
      zone2:
        ipv4_address: 124.10.0.100

networks:
  zone1:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/24"
        - gateway: "172.18.0.1"
  zone2:
    driver: bridge
    ipam:
      config:
        - subnet: "124.10.0.0/24"
        - gateway: "124.10.0.1"

volumes:
  tailnet-state:
