services:
  qemu:
    container_name: tailnet
    build: ..
    environment:
      BOOT: "/storage/boot.iso"
      ENGINE: "Podman"
      RAM_SIZE: "max"
      DISK_SIZE: "max"
      CPU_CORES: "max"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./storage:/storage
    restart: on-failure
    stop_grace_period: 2m
