services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: qemu-tty
    hostname: qemu-tty
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_SERVE_CONFIG=/config/ts-serve.json
    cap_add:
      - NET_ADMIN
    volumes:
      - tailnet-state:/var/lib/tailscale
      - ../web/conf:/config
    ports:
      - 8006:8006
    restart: always

  qemu:
    container_name: qemu
    build: ..
    image: tailnet-qemu:0.0.1-beta
    devices:
      - /dev/kvm
    privileged: true
    volumes:
      - ./qemu:/storage2
      - ./tmp:/storage
      - ..:/workspaces/tailnet-podman
    restart: on-failure
    stop_grace_period: 2m
    network_mode: service:tailscale
    depends_on:
      - tailscale

volumes:
  tailnet-state:
